services:
  mysql:
    image: mysql:8.0
    container_name: timefruit-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: timefruit
      MYSQL_USER: timefruit_user
      MYSQL_PASSWORD: timefruit_password
      MYSQL_ROOT_PASSWORD: timefruit_root_password
    networks:
      - timefruit-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "timefruit_user", "-ptimefruit_password"]
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timefruit-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=timefruit
      - DB_USER=timefruit_user
      - DB_PASSWORD=timefruit_password
    restart: unless-stopped
    networks:
      - timefruit-network
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timefruit-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_BACKEND_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - timefruit-network
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"

networks:
  timefruit-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
  mysql_data: